version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
